### ISSUE TITLE
What's the relation between this fpga-network-stack with fpgasystems/fpga-network-stack ?

### ISSUE THREAD

**Issue by LaceFern** [hpcn-uam/100G-fpga-network-stack-core#4]
Hello! Does this fpga-network-stack work at line rate? And what's the relation between this fpga-network-stack with [fpgasystems / fpga-network-stack](https://github.com/fpgasystems/fpga-network-stack)  ?

**Comment by mariodruiz** [comment]
Hi, your questions are answered in the paper that it is reference in the README, Limago.
