### ISSUE TITLE
ICMP myIpAddress port is not connected 

### ISSUE THREAD

**Issue by HongshiTan** [hpcn-uam/100G-fpga-network-stack-core#6]
I have encounter one issue that the myIpAddress port from ICMP server is not connected to the config input as shown in the following figure:

![Screenshot from 2023-08-25 16-16-16](https://github.com/hpcn-uam/100G-fpga-network-stack-core/assets/4355465/67c1ff9a-2c6e-4450-883a-d5405f7ba8b0)

It seems that the generated interface has duplicated suffix of "_0" with Vitis HLS 2022.2. This problem makes the FPGA failed to response ICMP package.

To fix it, I follow the code of ARP server,  and delete the pragma naming this port in icmp_server.cpp  

I'm not sure my solution is acceptable. If yes, I will push my change and open one PR to merge it.

Thanks

**Comment by mariodruiz** [comment]
Hi @HongshiTan,

Thank you for reporting this.
But, removing the pragma is not an option. This should be solved from VNx
